name: Release AddOn

on:
  push:
    tags:
      - '**'

env:
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: Package and release
        uses: BigWigsMods/packager@master
